apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-backend
  name: deployment-backend
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend
  strategy:    
  template:
    metadata:
      labels:
        app: deployment-backend
    spec:
      containers:
      - image: matheh1995/backend:1.0
        name: deployment-backend