apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-frontend
  name: service-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9000
  selector:
    app: deployment-backend
  type: NodePort
status:
  loadBalancer: {}
